parameters:
    ezobject_wrapper.ezobject_wrapper_factory.class: Kaliop\eZObjectWrapperBundle\Core\eZObjectWrapperFactory

services:
    ezobject_wrapper.services.factory:
        class: %ezobject_wrapper.ezobject_wrapper_factory.class%
        arguments: [@service_container]
    twig.extension.eZObjectWrapper:
        class: Kaliop\eZObjectWrapperBundle\Twig\eZObjectWrapperExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
